#!/bin/bash
set -euo pipefail

# Remote (Claude Code on the web) containers start from a fresh clone with no
# node_modules; local machines manage their own setup.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

cd "$CLAUDE_PROJECT_DIR"

# The harmoni-wasm pkg/ is generated by wasm-pack and gitignored; without it
# pnpm install fails with ERR_PNPM_WORKSPACE_PKG_NOT_FOUND, and wasm-pack is
# not available in this container (see the sandbox-gotchas skill). Stub the
# manifest just enough for workspace resolution — React unit tests never
# import harmoni-wasm, and the lockfile records this importer with no deps,
# so the stub causes no lockfile churn.
if [ ! -f crates/harmoni-wasm/pkg/package.json ]; then
  mkdir -p crates/harmoni-wasm/pkg
  cat > crates/harmoni-wasm/pkg/package.json << 'JSON'
{
  "name": "harmoni-wasm",
  "version": "0.0.0",
  "private": true,
  "description": "Install-time stub. The real pkg is generated by wasm-pack (pnpm run build:wasm); see the sandbox-gotchas skill."
}
JSON
  echo "session-start: stubbed crates/harmoni-wasm/pkg (wasm-pack unavailable in this container)"
fi

if [ ! -d node_modules ]; then
  # Frozen first so a fresh container never rewrites pnpm-lock.yaml; fall back
  # to a plain install (with a loud note) if the lockfile has drifted from the
  # workspace manifests.
  if ! pnpm install --frozen-lockfile; then
    echo "session-start: lockfile out of sync with workspace manifests — falling back to plain pnpm install (pnpm-lock.yaml will be modified; commit the sync separately)"
    pnpm install
  fi
fi

echo "session-start: dependencies ready"
