#!/bin/bash
set -euo pipefail

# Remote (Claude Code on the web) containers start from a fresh clone with no
# node_modules; local machines manage their own setup.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

cd "$CLAUDE_PROJECT_DIR"

# The harmoni-wasm pkg/ is generated by wasm-pack and gitignored; without it
# pnpm install fails with ERR_PNPM_WORKSPACE_PKG_NOT_FOUND, and wasm-pack is
# not available in this container (see the sandbox-gotchas skill). Stub the
# manifest for workspace resolution, and stub the module itself so the
# workbench's OklchPicker suite can run: those tests vi.mock("harmoni-wasm"),
# but Vite still has to *resolve* the specifier before the mock applies, and a
# manifest with no entry point fails that resolution — which silently took six
# of the fourteen picker test files out of action.
#
# The stub's exports are derived from the Rust source rather than hand-listed,
# so a new #[wasm_bindgen] entry point cannot go missing from it. Each throws:
# a test that forgets to mock gets a clear message instead of undefined.
if [ ! -f crates/harmoni-wasm/pkg/harmoni_wasm.js ]; then
  mkdir -p crates/harmoni-wasm/pkg
  cat > crates/harmoni-wasm/pkg/package.json << 'JSON'
{
  "name": "harmoni-wasm",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "main": "harmoni_wasm.js",
  "module": "harmoni_wasm.js",
  "description": "Install-time stub. The real pkg is generated by wasm-pack (pnpm run build:wasm); see the sandbox-gotchas skill."
}
JSON
  {
    echo "// Install-time stub - the real module is generated by wasm-pack."
    echo "// Exports exist so vi.mock('harmoni-wasm') can resolve the specifier."
    grep -A2 '#\[wasm_bindgen\]' crates/harmoni-wasm/src/lib.rs \
      | grep -oE '^pub fn [a-z_0-9]+' \
      | awk '{print $3}' | sort -u \
      | while read -r fn; do
          echo "export function $fn() { throw new Error('harmoni-wasm stub: run pnpm build:wasm, or vi.mock the module'); }"
        done
    echo "export default function init() { throw new Error('harmoni-wasm stub: run pnpm build:wasm'); }"
  } > crates/harmoni-wasm/pkg/harmoni_wasm.js
  echo "session-start: stubbed crates/harmoni-wasm/pkg (wasm-pack unavailable in this container)"
fi

if [ ! -d node_modules ]; then
  # Frozen first so a fresh container never rewrites pnpm-lock.yaml; fall back
  # to a plain install (with a loud note) if the lockfile has drifted from the
  # workspace manifests.
  if ! pnpm install --frozen-lockfile; then
    echo "session-start: lockfile out of sync with workspace manifests — falling back to plain pnpm install (pnpm-lock.yaml will be modified; commit the sync separately)"
    pnpm install
  fi
fi

echo "session-start: dependencies ready"
