// Generated by `primitiv tokens` — do not edit directly.
export const breakpoints = {
  "xs": "22.5rem",
  "sm": "40rem",
  "md": "48rem",
  "lg": "64rem",
  "xl": "80rem",
  "2xl": "96rem",
} as const;
