"use client";

import { Card, CardContent } from "@/components/card";

import sheet from "@/content/palette-sheet.generated.json";

import { useDocsTheme } from "./use-docs-theme";

import "./colour-proof.css";

/**
 * The home page's colour proof sheet — home copy §5, brief `COLOUR-01`.
 *
 * Six ramps of ten steps, with `Ag` on every swatch painted in the foreground
 * **the engine paired with it** and the step number beneath in the same colour.
 * The brief's argument is that this is the thing itself rather than a
 * demonstration of it: a reader scans a hundred swatches in three seconds and
 * sees that not one is hard to read, which no sentence achieves.
 *
 * Three things here are load-bearing.
 *
 * **Every colour comes from the engine, and none is computed here.** The data is
 * generated by `harmoni-core`'s `swatch-sheet` example through
 * `get_best_foreground`, and that example re-pairs all 100 generated swatches
 * identically before emitting anything. A black-or-white threshold in this file
 * would produce a visually similar sheet that is a lie about the exact thing the
 * section claims — the brief's first `must-not`.
 *
 * **The flip point is the evidence, so it is not tidied.** Where the foreground
 * changes from dark to light differs per ramp — warning flips at 600 in light
 * but 400 in dark, info at 600 and 500 — because the engine decided per swatch
 * rather than at a fixed midpoint. That raggedness is what shows something is
 * actually thinking.
 *
 * **Neutral is shown but not covered by the guarantee.** The 100-swatch CI guard
 * (`ramp_regression.rs`) covers the five generated ramps; neutral comes from the
 * `neutral` module and is not in the seed manifest. Showing it is right — it is
 * where most interface colour comes from — so the data carries a `generated`
 * flag per ramp and the prose states the scope, rather than a caption quietly
 * extending it.
 *
 * The sheet is a VISUAL proof of a claim the prose beside it makes in full, so
 * it is one `role="img"` with the brief's own alt text. Reading 120 "Ag"s and
 * step numbers aloud would add nothing a screen-reader user does not already
 * have from the paragraphs.
 */
const ALT =
  "The Primitiv colour palette — six ramps of ten steps each — with the letters " +
  '"Ag" on every swatch in the text colour the engine paired with it, and the ' +
  "step number beneath.";

type Row = {
  readonly ramp: string;
  readonly generated: boolean;
  readonly steps: readonly { step: string; hex: string; foreground: string }[];
};

const SHEET: Record<string, readonly Row[]> = sheet;

export const ColourProof = () => {
  const [theme] = useDocsTheme();
  /* The two themes are genuinely different colour values, not one sheet dimmed
     — and a reader toggling the site theme and seeing both hold is itself part
     of the proof. Which is why this follows `useDocsTheme` rather than being
     two sheets swapped by CSS. */
  const rows = SHEET[theme] ?? SHEET.light;

  return (
    <Card className="docs-colour-proof">
      <CardContent>
        <div className="docs-colour-sheet" role="img" aria-label={ALT}>
          {rows.map((row) => (
            <div className="docs-colour-row" key={row.ramp}>
              <span className="docs-colour-ramp-name">{row.ramp}</span>
              {/* Flush, with no gap between swatches — that is what makes a row
                  read as one continuous scale rather than ten chips. */}
              <div className="docs-colour-steps">
                {row.steps.map((s) => (
                  <div
                    className="docs-colour-swatch"
                    key={s.step}
                    style={{ background: s.hex, color: s.foreground }}
                  >
                    <span className="docs-colour-sample">Ag</span>
                    <span className="docs-colour-step">{s.step}</span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
};
