mod types;

use wasm_bindgen::prelude::*;
use js_sys::Array;

use harmoni_core::api::{self, GenerateOptions};
use harmoni_core::ColorInput;

fn to_js_error(e: impl std::fmt::Debug) -> JsError {
    JsError::new(&format!("Invalid color input: {:?}", e))
}

fn array_to_lightness(js_array: Array) -> Result<[f32; 10], JsError> {
    if js_array.length() != 10 {
        return Err(JsError::new(&format!(
            "Lightness array must have exactly 10 values, got {}",
            js_array.length()
        )));
    }

    let mut lightness = [0.0f32; 10];
    for i in 0..10 {
        let value = js_array.get(i as u32);
        let f = value
            .as_f64()
            .ok_or_else(|| JsError::new(&format!("Lightness at index {} is not a number", i)))?
            as f32;
        lightness[i] = f;
    }

    Ok(lightness)
}

fn palette_to_js(palette_data: harmoni_core::Palette) -> Result<Palette, JsError> {
    let wrapped: types::Palette = palette_data.into();
    serde_wasm_bindgen::to_value(&wrapped)
        .map(|v| v.unchecked_into())
        .map_err(|e| JsError::new(&e.to_string()))
}

// Palette is generated by Tsify as a struct interface:
// { swatches: Swatch[], max_recommended_light_padding: number, ... }
// Tsify automatically emits this to the generated .d.ts file via the
// #[tsify] derive on `types::Palette`.

#[wasm_bindgen]
extern "C" {
    // Opaque JS handle whose TS type is `Palette` (= Swatch[]).
    // Needed because Vec<T> is not a first-class wasm-abi return type.
    #[wasm_bindgen(typescript_type = "Palette")]
    pub type Palette;
}

#[wasm_bindgen]
pub fn get_contrast_rating(bg: &str, fg: &str) -> Result<types::ContrastResult, JsError> {
    api::audit_contrast(
        ColorInput::Css(bg.to_string()),
        ColorInput::Css(fg.to_string()),
    )
    .map(Into::into)
    .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn generate_palette(
    hex: &str,
    light_padding: f32,
    dark_padding: f32,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_with_options(
        ColorInput::Css(hex.to_string()),
        GenerateOptions {
            light_padding,
            dark_padding,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn generate_palette_with_lightness(
    hex: &str,
    lightness: Array,
    light_padding: f32,
    dark_padding: f32,
) -> Result<Palette, JsError> {
    let lightness_curve = array_to_lightness(lightness)?;

    let palette_data = api::generate_with_lightness(
        ColorInput::Css(hex.to_string()),
        lightness_curve,
        GenerateOptions {
            light_padding,
            dark_padding,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn generate_palette_pair(
    hex: &str,
    light_lightness: Array,
    dark_lightness: Array,
    light_padding: f32,
    dark_padding: f32,
) -> Result<types::PaletteSet, JsError> {
    let light_curve = array_to_lightness(light_lightness)?;
    let dark_curve = array_to_lightness(dark_lightness)?;

    api::generate_pair(
        ColorInput::Css(hex.to_string()),
        &light_curve,
        &dark_curve,
        GenerateOptions {
            light_padding,
            dark_padding,
            ..GenerateOptions::default()
        },
    )
    .map(Into::into)
    .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn generate_palette_with_light_padding(
    hex: &str,
    light_padding: f32,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_with_options(
        ColorInput::Css(hex.to_string()),
        GenerateOptions {
            light_padding,
            dark_padding: 0.0,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn generate_neutral_ramp(
    white: &str,
    black: &str,
    tint: types::TintMode,
    bow: f32,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_neutral_ramp(
        ColorInput::Css(white.to_string()),
        ColorInput::Css(black.to_string()),
        tint.into(),
        harmoni_core::RampOptions { bow },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

/// Builds an alpha ramp from a single anchor colour (Path A): the anchor held
/// constant across ten steps while opacity climbs the shared curve. Neutral
/// ramps pass their veil colour (soft-black in light, soft-white in dark);
/// brand ramps pass the brand's identity swatch.
#[wasm_bindgen]
pub fn generate_alpha_ramp(anchor: &str) -> Result<types::AlphaRamp, JsError> {
    api::generate_alpha_ramp(ColorInput::Css(anchor.to_string()))
        .map(Into::into)
        .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn derive_soft_neutrals(
    brand: &str,
    softness: f32,
) -> Result<types::SoftNeutrals, JsError> {
    api::derive_soft_neutrals(ColorInput::Css(brand.to_string()), softness)
        .map(Into::into)
        .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn tint_neutrals(
    white: &str,
    black: &str,
    source: &str,
    strength: f32,
) -> Result<types::SoftNeutrals, JsError> {
    api::tint_neutrals(
        ColorInput::Css(white.to_string()),
        ColorInput::Css(black.to_string()),
        ColorInput::Css(source.to_string()),
        strength,
    )
    .map(Into::into)
    .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn tint_neutrals_duotone(
    white: &str,
    black: &str,
    highlight: &str,
    shadow: &str,
    strength: f32,
) -> Result<types::SoftNeutrals, JsError> {
    api::tint_neutrals_duotone(
        ColorInput::Css(white.to_string()),
        ColorInput::Css(black.to_string()),
        ColorInput::Css(highlight.to_string()),
        ColorInput::Css(shadow.to_string()),
        strength,
    )
    .map(Into::into)
    .map_err(to_js_error)
}

/// The maximum in-gamut chroma for an OkLCH lightness and hue, against the given
/// `gamut` (sRGB or Display-P3) — the boundary curve the OKLCH picker overlays on
/// its charts and clamps the cursor to (RFC 0010 §3, §7).
#[wasm_bindgen]
pub fn max_in_gamut_chroma(lightness: f32, hue: f32, gamut: types::Gamut) -> f32 {
    api::max_in_gamut_chroma(lightness, hue, gamut.into())
}

/// Paints the OkLCH lightness×chroma plane for a fixed hue as a flat RGBA
/// buffer (`width * height * 4` bytes, row-major) the canvas blits straight
/// into `ImageData`. Pixels carry `gamut` coordinates; out-of-gamut pixels are
/// transparent (RFC 0010 §3, §7).
#[wasm_bindgen]
pub fn paint_lc_plane(
    hue: f32,
    width: usize,
    height: usize,
    c_max: f32,
    gamut: types::Gamut,
) -> Vec<u8> {
    api::paint_lc_plane(hue, width, height, c_max, gamut.into())
}

/// Paints the OkLCH chroma×hue plane for a fixed lightness as a flat RGBA buffer
/// (`width * height * 4` bytes, row-major) — the picker's Lightness chart. Hue
/// runs left→right, chroma top→bottom; out-of-gamut pixels are transparent
/// (RFC 0010 §3, §7).
#[wasm_bindgen]
pub fn paint_ch_plane(
    lightness: f32,
    width: usize,
    height: usize,
    c_max: f32,
    gamut: types::Gamut,
) -> Vec<u8> {
    api::paint_ch_plane(lightness, width, height, c_max, gamut.into())
}

/// Paints the OkLCH lightness×hue plane for a fixed chroma as a flat RGBA buffer
/// (`width * height * 4` bytes, row-major) — the picker's Chroma chart. Hue runs
/// left→right, lightness top→bottom; out-of-gamut pixels are transparent
/// (RFC 0010 §3, §7).
#[wasm_bindgen]
pub fn paint_lh_plane(chroma: f32, width: usize, height: usize, gamut: types::Gamut) -> Vec<u8> {
    api::paint_lh_plane(chroma, width, height, gamut.into())
}

/// Paints the hue spectrum at a fixed lightness and chroma against `gamut` as a
/// flat RGBA buffer (`width * 4` bytes) for the picker's hue slider track
/// (RFC 0010 §3, §7).
#[wasm_bindgen]
pub fn paint_hue_strip(lightness: f32, chroma: f32, width: usize, gamut: types::Gamut) -> Vec<u8> {
    api::paint_hue_strip(lightness, chroma, width, gamut.into())
}

/// Paints the lightness sweep at a fixed chroma and hue against `gamut` as a flat
/// RGBA buffer (`width * 4` bytes) for the picker's L slider track (RFC 0010 §7).
#[wasm_bindgen]
pub fn paint_lightness_strip(
    chroma: f32,
    hue: f32,
    width: usize,
    gamut: types::Gamut,
    l_min: f32,
    l_max: f32,
) -> Vec<u8> {
    api::paint_lightness_strip(chroma, hue, width, gamut.into(), l_min, l_max)
}

/// Paints the chroma sweep at a fixed lightness and hue against `gamut` as a flat
/// RGBA buffer (`width * 4` bytes) for the picker's C slider track (RFC 0010 §7).
#[wasm_bindgen]
pub fn paint_chroma_strip(
    lightness: f32,
    hue: f32,
    width: usize,
    c_max: f32,
    gamut: types::Gamut,
) -> Vec<u8> {
    api::paint_chroma_strip(lightness, hue, width, c_max, gamut.into())
}

/// Parses any CSS colour string (`#rrggbb`, `oklch(L C H)`, `rgb(...)`, a
/// named colour, …) into the OkLCH triple the picker's hex⇄oklch text field
/// round-trips through — `{ l, c, h }` plus the `hex`/`rgb`/`oklch` renderings
/// (RFC 0010 §4). Parsing crosses into the one Rust engine; no JS colour
/// library is involved (Principle 1). Errors on an unparseable string.
#[wasm_bindgen]
pub fn parse_color(input: &str) -> Result<types::OklchTriple, JsError> {
    let oklch = ColorInput::Css(input.to_string())
        .to_oklch()
        .map_err(to_js_error)?;
    Ok(types::oklch_triple(oklch))
}

/// Renders an OkLCH `{ l, c, h }` triple back into the engine's canonical
/// `hex`/`rgb`/`oklch` strings, so the picker formats its current value through
/// the same source of truth it parses with (RFC 0010 §4).
#[wasm_bindgen]
pub fn describe_oklch(l: f32, c: f32, h: f32) -> types::OklchTriple {
    types::oklch_triple(palette::Oklch::new(l, c, h))
}
