mod types;

use wasm_bindgen::prelude::*;
use js_sys::Array;

use harmoni_core::api::{self, GenerateOptions};
use harmoni_core::ColorInput;

fn to_js_error(e: impl std::fmt::Debug) -> JsError {
    JsError::new(&format!("Invalid color input: {:?}", e))
}

fn array_to_lightness(js_array: Array) -> Result<[f32; 10], JsError> {
    if js_array.length() != 10 {
        return Err(JsError::new(&format!(
            "Lightness array must have exactly 10 values, got {}",
            js_array.length()
        )));
    }

    let mut lightness = [0.0f32; 10];
    for i in 0..10 {
        let value = js_array.get(i as u32);
        let f = value
            .as_f64()
            .ok_or_else(|| JsError::new(&format!("Lightness at index {} is not a number", i)))?
            as f32;
        lightness[i] = f;
    }

    Ok(lightness)
}

fn palette_to_js(palette_data: harmoni_core::Palette) -> Result<Palette, JsError> {
    let wrapped: types::Palette = palette_data.into();
    serde_wasm_bindgen::to_value(&wrapped)
        .map(|v| v.unchecked_into())
        .map_err(|e| JsError::new(&e.to_string()))
}

// Palette is generated by Tsify as a struct interface:
// { swatches: Swatch[], max_recommended_light_padding: number, ... }
// Tsify automatically emits this to the generated .d.ts file via the
// #[tsify] derive on `types::Palette`.

#[wasm_bindgen]
extern "C" {
    // Opaque JS handle whose TS type is `Palette` (= Swatch[]).
    // Needed because Vec<T> is not a first-class wasm-abi return type.
    #[wasm_bindgen(typescript_type = "Palette")]
    pub type Palette;
}

#[wasm_bindgen]
pub fn get_contrast_rating(bg: &str, fg: &str) -> Result<types::ContrastResult, JsError> {
    api::audit_contrast(
        ColorInput::Css(bg.to_string()),
        ColorInput::Css(fg.to_string()),
    )
    .map(Into::into)
    .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn generate_palette(
    hex: &str,
    light_padding: f32,
    dark_padding: f32,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_with_options(
        ColorInput::Css(hex.to_string()),
        GenerateOptions {
            light_padding,
            dark_padding,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn generate_palette_with_lightness(
    hex: &str,
    lightness: Array,
    light_padding: f32,
    dark_padding: f32,
) -> Result<Palette, JsError> {
    let lightness_curve = array_to_lightness(lightness)?;

    let palette_data = api::generate_with_lightness(
        ColorInput::Css(hex.to_string()),
        lightness_curve,
        GenerateOptions {
            light_padding,
            dark_padding,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn generate_palette_pair(
    hex: &str,
    light_lightness: Array,
    dark_lightness: Array,
    light_padding: f32,
    dark_padding: f32,
) -> Result<types::PaletteSet, JsError> {
    let light_curve = array_to_lightness(light_lightness)?;
    let dark_curve = array_to_lightness(dark_lightness)?;

    api::generate_pair(
        ColorInput::Css(hex.to_string()),
        &light_curve,
        &dark_curve,
        GenerateOptions {
            light_padding,
            dark_padding,
            ..GenerateOptions::default()
        },
    )
    .map(Into::into)
    .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn generate_palette_with_light_padding(
    hex: &str,
    light_padding: f32,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_with_options(
        ColorInput::Css(hex.to_string()),
        GenerateOptions {
            light_padding,
            dark_padding: 0.0,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn generate_neutral_ramp(
    white: &str,
    black: &str,
    tint: types::TintMode,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_neutral_ramp(
        ColorInput::Css(white.to_string()),
        ColorInput::Css(black.to_string()),
        tint.into(),
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn derive_soft_neutrals(
    brand: &str,
    softness: f32,
) -> Result<types::SoftNeutrals, JsError> {
    api::derive_soft_neutrals(ColorInput::Css(brand.to_string()), softness)
        .map(Into::into)
        .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn tint_neutrals(
    white: &str,
    black: &str,
    source: &str,
    strength: f32,
) -> Result<types::SoftNeutrals, JsError> {
    api::tint_neutrals(
        ColorInput::Css(white.to_string()),
        ColorInput::Css(black.to_string()),
        ColorInput::Css(source.to_string()),
        strength,
    )
    .map(Into::into)
    .map_err(to_js_error)
}

/// The maximum in-sRGB-gamut chroma for an OkLCH lightness and hue — the
/// boundary curve the OKLCH picker overlays on its charts (RFC 0010).
#[wasm_bindgen]
pub fn max_in_gamut_chroma(lightness: f32, hue: f32) -> f32 {
    api::max_in_gamut_chroma(lightness, hue, api::Gamut::Srgb)
}

/// Paints the OkLCH lightness×chroma plane for a fixed hue as a flat RGBA
/// buffer (`width * height * 4` bytes, row-major) the canvas blits straight
/// into `ImageData`. Out-of-gamut pixels are transparent (RFC 0010 §3).
#[wasm_bindgen]
pub fn paint_lc_plane(hue: f32, width: usize, height: usize, c_max: f32) -> Vec<u8> {
    api::paint_lc_plane(hue, width, height, c_max, api::Gamut::Srgb)
}

/// Paints the hue spectrum at a fixed lightness and chroma as a flat RGBA
/// buffer (`width * 4` bytes) for the picker's hue slider (RFC 0010 §3).
#[wasm_bindgen]
pub fn paint_hue_strip(lightness: f32, chroma: f32, width: usize) -> Vec<u8> {
    api::paint_hue_strip(lightness, chroma, width, api::Gamut::Srgb)
}

/// Parses any CSS colour string (`#rrggbb`, `oklch(L C H)`, `rgb(...)`, a
/// named colour, …) into the OkLCH triple the picker's hex⇄oklch text field
/// round-trips through — `{ l, c, h }` plus the `hex`/`rgb`/`oklch` renderings
/// (RFC 0010 §4). Parsing crosses into the one Rust engine; no JS colour
/// library is involved (Principle 1). Errors on an unparseable string.
#[wasm_bindgen]
pub fn parse_color(input: &str) -> Result<types::OklchTriple, JsError> {
    let oklch = ColorInput::Css(input.to_string())
        .to_oklch()
        .map_err(to_js_error)?;
    Ok(types::oklch_triple(oklch))
}

/// Renders an OkLCH `{ l, c, h }` triple back into the engine's canonical
/// `hex`/`rgb`/`oklch` strings, so the picker formats its current value through
/// the same source of truth it parses with (RFC 0010 §4).
#[wasm_bindgen]
pub fn describe_oklch(l: f32, c: f32, h: f32) -> types::OklchTriple {
    types::oklch_triple(palette::Oklch::new(l, c, h))
}
