mod types;

use wasm_bindgen::prelude::*;
use js_sys::Array;

use harmoni_core::api::{self, GenerateOptions};
use harmoni_core::ColorInput;

fn to_js_error(e: impl std::fmt::Debug) -> JsError {
    JsError::new(&format!("Invalid color input: {:?}", e))
}

/// The checks behind [`array_to_lightness`], split from the `Array` that
/// carries them. A JS array cannot be built off-target, so the iteration below
/// is only reachable under a wasm runtime — but the length and per-index rules
/// are the part that can actually be wrong, and this keeps them reachable.
fn lightness_from_values(values: &[Option<f64>]) -> Result<[f32; 10], String> {
    if values.len() != 10 {
        return Err(format!(
            "Lightness array must have exactly 10 values, got {}",
            values.len()
        ));
    }

    let mut lightness = [0.0f32; 10];
    for (i, value) in values.iter().enumerate() {
        lightness[i] =
            value.ok_or_else(|| format!("Lightness at index {} is not a number", i))? as f32;
    }

    Ok(lightness)
}

fn array_to_lightness(js_array: Array) -> Result<[f32; 10], JsError> {
    let values: Vec<Option<f64>> = (0..js_array.length())
        .map(|i| js_array.get(i).as_f64())
        .collect();

    lightness_from_values(&values).map_err(|message| JsError::new(&message))
}

fn palette_to_js(palette_data: harmoni_core::Palette) -> Result<Palette, JsError> {
    let wrapped: types::Palette = palette_data.into();
    serde_wasm_bindgen::to_value(&wrapped)
        .map(|v| v.unchecked_into())
        .map_err(|e| JsError::new(&e.to_string()))
}

// Palette is generated by Tsify as a struct interface:
// { swatches: Swatch[], max_recommended_light_padding: number, ... }
// Tsify automatically emits this to the generated .d.ts file via the
// #[tsify] derive on `types::Palette`.

#[wasm_bindgen]
extern "C" {
    // Opaque JS handle whose TS type is `Palette` (= Swatch[]).
    // Needed because Vec<T> is not a first-class wasm-abi return type.
    #[wasm_bindgen(typescript_type = "Palette")]
    pub type Palette;

}

#[wasm_bindgen]
pub fn get_contrast_rating(bg: &str, fg: &str) -> Result<types::ContrastResult, JsError> {
    api::audit_contrast(
        ColorInput::Css(bg.to_string()),
        ColorInput::Css(fg.to_string()),
    )
    .map(Into::into)
    .map_err(to_js_error)
}

/// The step of `ramp` to use for a role that must clear `threshold` against
/// `surface` — a link colour, a muted-text colour, a border.
///
/// Returns the **quietest** step that clears, not the first: a role wants the
/// least contrast that still passes, because a border pushed to body-text
/// weight passes its floor and looks like a mistake. `None` where nothing in
/// the ramp reaches the threshold, rather than the least bad option.
///
/// This is the question `get_best_foreground` cannot answer — that one draws
/// from the ramp's ends and the white/black anchors, so it has nothing to say
/// about which *mid-ramp* step is readable on some *other* surface.
#[wasm_bindgen]
pub fn readable_step(
    ramp: types::Ramp,
    surface: types::SwatchStep,
    threshold: f32,
) -> Option<types::ReadableStep> {
    let steps: Vec<harmoni_core::SwatchStep> =
        ramp.steps.into_iter().map(Into::into).collect();

    api::readable_step(&steps, &surface.into(), threshold).map(Into::into)
}

/// Sample a curve preset at `count` positions, normalised to `0..=1` ascending.
///
/// This is the shape itself, not a ramp: what a preview glyph draws, and what a
/// chart plots before the ramp's own endpoints are applied to it.
#[wasm_bindgen]
pub fn curve_samples(preset: types::CurvePreset, count: usize) -> Vec<f32> {
    api::curve(&preset.into(), count)
}

/// The accent at which `Arc` is a shape of its own.
///
/// Both ends of the accent range duplicate `Sine` — 0 is its ease-out, 1 its
/// ease-in — so the default is a real engine decision rather than a midpoint
/// picked for tidiness. A control that hardcodes it drifts the moment the
/// engine changes its mind, the same argument as `supported_step_range`.
#[wasm_bindgen]
pub fn default_arc_accent() -> f32 {
    api::DEFAULT_ARC_ACCENT
}

/// What `ratio` achieves when the colour is used as `use`.
///
/// `get_contrast_rating` answers a different question — it reports a ratio and
/// a single stringly-typed rating, which cannot say that one ratio is AA as
/// body copy, AAA at heading size, and past the non-text bar all at once. A
/// grade is what a designer decides on; compose this with the ratio from
/// `get_contrast_rating` when the evidence behind the verdict is wanted too.
#[wasm_bindgen]
pub fn grade(ratio: f32, r#use: types::ContrastUse) -> types::Grade {
    api::grade(ratio, r#use.into()).into()
}

#[wasm_bindgen]
pub fn generate_palette(
    hex: &str,
    light_padding: f32,
    dark_padding: f32,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_with_options(
        ColorInput::Css(hex.to_string()),
        GenerateOptions {
            light_padding,
            dark_padding,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn generate_palette_with_lightness(
    hex: &str,
    lightness: Array,
    light_padding: f32,
    dark_padding: f32,
) -> Result<Palette, JsError> {
    let lightness_curve = array_to_lightness(lightness)?;

    let palette_data = api::generate_with_lightness(
        ColorInput::Css(hex.to_string()),
        lightness_curve,
        GenerateOptions {
            light_padding,
            dark_padding,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

/// The ramp lengths the engine supports, as `[min, default, max]` — what a
/// step-count control should bound itself to rather than hardcoding.
#[wasm_bindgen]
pub fn supported_step_range() -> Vec<usize> {
    vec![api::MIN_STEPS, api::DEFAULT_STEPS, api::MAX_STEPS]
}

/// Generate a light palette of `steps` steps, reading the built-in curves at
/// that resolution. `steps` outside the supported range is an error rather
/// than being clamped, so a caller finds out it asked for the impossible.
#[wasm_bindgen]
pub fn generate_palette_with_steps(
    hex: &str,
    steps: usize,
    light_padding: f32,
    dark_padding: f32,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_with_options(
        ColorInput::Css(hex.to_string()),
        GenerateOptions {
            light_padding,
            dark_padding,
            steps,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

/// A light/dark pair of `steps` steps each, from the built-in curves.
#[wasm_bindgen]
pub fn generate_palette_pair_with_steps(
    hex: &str,
    steps: usize,
    light_padding: f32,
    dark_padding: f32,
) -> Result<types::PaletteSet, JsError> {
    api::generate_brand_pair_with_options(
        ColorInput::Css(hex.to_string()),
        GenerateOptions {
            light_padding,
            dark_padding,
            steps,
            ..GenerateOptions::default()
        },
    )
    .map(Into::into)
    .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn generate_palette_pair(
    hex: &str,
    light_lightness: Array,
    dark_lightness: Array,
    light_padding: f32,
    dark_padding: f32,
) -> Result<types::PaletteSet, JsError> {
    let light_curve = array_to_lightness(light_lightness)?;
    let dark_curve = array_to_lightness(dark_lightness)?;

    api::generate_pair(
        ColorInput::Css(hex.to_string()),
        &light_curve,
        &dark_curve,
        GenerateOptions {
            light_padding,
            dark_padding,
            ..GenerateOptions::default()
        },
    )
    .map(Into::into)
    .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn generate_palette_with_light_padding(
    hex: &str,
    light_padding: f32,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_with_options(
        ColorInput::Css(hex.to_string()),
        GenerateOptions {
            light_padding,
            dark_padding: 0.0,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn generate_neutral_ramp(
    white: &str,
    black: &str,
    tint: types::TintMode,
    bow: f32,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_neutral_ramp(
        ColorInput::Css(white.to_string()),
        ColorInput::Css(black.to_string()),
        tint.into(),
        harmoni_core::RampOptions { bow },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

/// Builds an alpha ramp from a single anchor colour (Path A): the anchor held
/// constant across ten steps while opacity climbs the shared curve. Neutral
/// ramps pass their veil colour (soft-black in light, soft-white in dark);
/// brand ramps pass the brand's identity swatch.
#[wasm_bindgen]
pub fn generate_alpha_ramp(anchor: &str) -> Result<types::AlphaRamp, JsError> {
    api::generate_alpha_ramp(ColorInput::Css(anchor.to_string()))
        .map(Into::into)
        .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn derive_soft_neutrals(
    brand: &str,
    softness: f32,
) -> Result<types::SoftNeutrals, JsError> {
    api::derive_soft_neutrals(ColorInput::Css(brand.to_string()), softness)
        .map(Into::into)
        .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn tint_neutrals(
    white: &str,
    black: &str,
    source: &str,
    strength: f32,
) -> Result<types::SoftNeutrals, JsError> {
    api::tint_neutrals(
        ColorInput::Css(white.to_string()),
        ColorInput::Css(black.to_string()),
        ColorInput::Css(source.to_string()),
        strength,
    )
    .map(Into::into)
    .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn tint_neutrals_duotone(
    white: &str,
    black: &str,
    highlight: &str,
    shadow: &str,
    strength: f32,
) -> Result<types::SoftNeutrals, JsError> {
    api::tint_neutrals_duotone(
        ColorInput::Css(white.to_string()),
        ColorInput::Css(black.to_string()),
        ColorInput::Css(highlight.to_string()),
        ColorInput::Css(shadow.to_string()),
        strength,
    )
    .map(Into::into)
    .map_err(to_js_error)
}

/// The maximum in-gamut chroma for an OkLCH lightness and hue, against the given
/// `gamut` (sRGB or Display-P3) — the boundary curve the OKLCH picker overlays on
/// its charts and clamps the cursor to (RFC 0010 §3, §7).
#[wasm_bindgen]
pub fn max_in_gamut_chroma(lightness: f32, hue: f32, gamut: types::Gamut) -> f32 {
    api::max_in_gamut_chroma(lightness, hue, gamut.into())
}

/// Paints the OkLCH lightness×chroma plane for a fixed hue as a flat RGBA
/// buffer (`width * height * 4` bytes, row-major) the canvas blits straight
/// into `ImageData`. Pixels carry `gamut` coordinates; out-of-gamut pixels are
/// transparent (RFC 0010 §3, §7).
#[wasm_bindgen]
pub fn paint_lc_plane(
    hue: f32,
    width: usize,
    height: usize,
    c_max: f32,
    gamut: types::Gamut,
) -> Vec<u8> {
    api::paint_lc_plane(hue, width, height, c_max, gamut.into())
}

/// Paints the OkLCH chroma×hue plane for a fixed lightness as a flat RGBA buffer
/// (`width * height * 4` bytes, row-major) — the picker's Lightness chart. Hue
/// runs left→right, chroma top→bottom; out-of-gamut pixels are transparent
/// (RFC 0010 §3, §7).
#[wasm_bindgen]
pub fn paint_ch_plane(
    lightness: f32,
    width: usize,
    height: usize,
    c_max: f32,
    gamut: types::Gamut,
) -> Vec<u8> {
    api::paint_ch_plane(lightness, width, height, c_max, gamut.into())
}

/// Paints the OkLCH lightness×hue plane for a fixed chroma as a flat RGBA buffer
/// (`width * height * 4` bytes, row-major) — the picker's Chroma chart. Hue runs
/// left→right, lightness top→bottom; out-of-gamut pixels are transparent
/// (RFC 0010 §3, §7).
#[wasm_bindgen]
pub fn paint_lh_plane(chroma: f32, width: usize, height: usize, gamut: types::Gamut) -> Vec<u8> {
    api::paint_lh_plane(chroma, width, height, gamut.into())
}

/// Paints the hue spectrum at a fixed lightness and chroma against `gamut` as a
/// flat RGBA buffer (`width * 4` bytes) for the picker's hue slider track
/// (RFC 0010 §3, §7).
#[wasm_bindgen]
pub fn paint_hue_strip(lightness: f32, chroma: f32, width: usize, gamut: types::Gamut) -> Vec<u8> {
    api::paint_hue_strip(lightness, chroma, width, gamut.into())
}

/// Paints the lightness sweep at a fixed chroma and hue against `gamut` as a flat
/// RGBA buffer (`width * 4` bytes) for the picker's L slider track (RFC 0010 §7).
#[wasm_bindgen]
pub fn paint_lightness_strip(
    chroma: f32,
    hue: f32,
    width: usize,
    gamut: types::Gamut,
    l_min: f32,
    l_max: f32,
) -> Vec<u8> {
    api::paint_lightness_strip(chroma, hue, width, gamut.into(), l_min, l_max)
}

/// Paints the chroma sweep at a fixed lightness and hue against `gamut` as a flat
/// RGBA buffer (`width * 4` bytes) for the picker's C slider track (RFC 0010 §7).
#[wasm_bindgen]
pub fn paint_chroma_strip(
    lightness: f32,
    hue: f32,
    width: usize,
    c_max: f32,
    gamut: types::Gamut,
) -> Vec<u8> {
    api::paint_chroma_strip(lightness, hue, width, c_max, gamut.into())
}

/// Parses any CSS colour string (`#rrggbb`, `oklch(L C H)`, `rgb(...)`, a
/// named colour, …) into the OkLCH triple the picker's hex⇄oklch text field
/// round-trips through — `{ l, c, h }` plus the `hex`/`rgb`/`oklch` renderings
/// (RFC 0010 §4). Parsing crosses into the one Rust engine; no JS colour
/// library is involved (Principle 1). Errors on an unparseable string.
/// Generates the ramp this OkLCH colour would seed and measures what it can
/// actually do in `gamut` — chroma the steps get versus what they ask for, hue
/// held versus rendered, step spacing, and foreground coverage.
///
/// This is the picker's feedback source (RFC 0027 §6): the data is already on
/// screen as a gamut boundary, it was simply never interpreted. Call it once per
/// gamut to state the trade-off — the same hue that mutes badly in sRGB may be
/// comfortable in Display-P3.
#[wasm_bindgen]
pub fn assess_brand_ramp(
    l: f32,
    c: f32,
    h: f32,
    gamut: types::Gamut,
) -> Result<types::RampQuality, JsError> {
    let palette = api::generate(ColorInput::Oklch { l, c, h }).map_err(to_js_error)?;
    Ok(api::assess_ramp(&palette, gamut.into()).into())
}

/// Per-step chroma headroom for the ramp this colour would seed: what each
/// step's scale asks for, against what the gamut grants. The gap is what tells a
/// designer their hue will mute — and where (RFC 0027 §6).
#[wasm_bindgen]
pub fn chroma_headroom(
    l: f32,
    c: f32,
    h: f32,
    gamut: types::Gamut,
) -> types::ChromaHeadroomReport {
    types::ChromaHeadroomReport {
        steps: api::chroma_headroom(palette::Oklch::new(l, c, h), 0.0, 0.0, gamut.into())
            .into_iter()
            .map(Into::into)
            .collect(),
    }
}

#[wasm_bindgen]
pub fn parse_color(input: &str) -> Result<types::OklchTriple, JsError> {
    let oklch = ColorInput::Css(input.to_string())
        .to_oklch()
        .map_err(to_js_error)?;
    Ok(types::oklch_triple(oklch))
}

/// Renders an OkLCH `{ l, c, h }` triple back into the engine's canonical
/// `hex`/`rgb`/`oklch` strings, so the picker formats its current value through
/// the same source of truth it parses with (RFC 0010 §4).
#[wasm_bindgen]
pub fn describe_oklch(l: f32, c: f32, h: f32) -> types::OklchTriple {
    types::oklch_triple(palette::Oklch::new(l, c, h))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The example the design note turns on: one ratio, three verdicts. A
    /// stringly-typed `rating` cannot express this, which is why the boundary
    /// needed the use-aware grade rather than only `get_contrast_rating`.
    #[test]
    fn a_lightness_curve_of_the_wrong_length_says_what_it_actually_got() {
        let five = vec![Some(0.5); 5];
        assert_eq!(
            lightness_from_values(&five),
            Err("Lightness array must have exactly 10 values, got 5".to_string())
        );
    }

    #[test]
    fn a_non_numeric_lightness_names_the_index_that_is_wrong() {
        // Without the index a caller has ten candidates and no way to tell
        // which one it handed over.
        let mut values = vec![Some(0.5); 10];
        values[7] = None;
        assert_eq!(
            lightness_from_values(&values),
            Err("Lightness at index 7 is not a number".to_string())
        );
    }

    #[test]
    fn a_well_formed_lightness_curve_narrows_to_a_fixed_array() {
        let values: Vec<Option<f64>> = (0..10).map(|i| Some(i as f64 / 10.0)).collect();
        let curve = lightness_from_values(&values).expect("ten numbers is a valid curve");
        assert_eq!(curve.len(), 10);
        assert_eq!(curve[0], 0.0);
        assert_eq!(curve[9], 0.9);
    }

    fn preset(easing: types::Easing, direction: types::Direction) -> types::CurvePreset {
        types::CurvePreset { easing, direction, accent: default_arc_accent() }
    }

    #[test]
    fn sampling_a_preset_spans_the_unit_interval_end_to_end() {
        let samples = curve_samples(preset(types::Easing::Sine, types::Direction::EaseInOut), 10);

        assert_eq!(samples.len(), 10);
        assert_eq!(samples.first().copied(), Some(0.0));
        assert_eq!(samples.last().copied(), Some(1.0));
    }

    #[test]
    fn the_arc_accent_default_comes_from_the_engine_not_the_ui() {
        // Both ends of the accent range duplicate Sine, so the default is a
        // real engine decision. A control that hardcodes 0.5 drifts silently
        // the moment the engine changes its mind.
        let accent = default_arc_accent();
        assert!((0.0..=1.0).contains(&accent));

        let at_default = curve_samples(preset(types::Easing::Arc, types::Direction::EaseOut), 5);
        let at_zero = curve_samples(
            types::CurvePreset { accent: 0.0, ..preset(types::Easing::Arc, types::Direction::EaseOut) },
            5,
        );
        assert_ne!(at_default, at_zero, "the default accent is the degenerate one");
    }

    #[test]
    fn the_accent_only_moves_the_arc() {
        let a = curve_samples(
            types::CurvePreset { accent: 0.0, ..preset(types::Easing::Sine, types::Direction::EaseIn) },
            6,
        );
        let b = curve_samples(
            types::CurvePreset { accent: 1.0, ..preset(types::Easing::Sine, types::Direction::EaseIn) },
            6,
        );
        assert_eq!(a, b, "accent leaked into a family that does not take one");
    }

    const BRAND: &str = "#3b82f6";
    const NONSENSE: &str = "not-a-colour";

    #[test]
    fn black_on_white_is_the_maximum_contrast_the_standard_defines() {
        let result = get_contrast_rating("#ffffff", "#000000").unwrap();
        assert_eq!(result.ratio.round(), 21.0);
        assert!(!result.display_ratio.is_empty());
    }

    #[test]
    fn the_step_range_is_reported_so_a_control_need_not_hardcode_it() {
        assert_eq!(supported_step_range(), vec![3, 10, 32]);
    }

    #[test]
    fn a_pair_gives_both_themes_at_the_length_that_was_asked_for() {
        let pair = generate_palette_pair_with_steps(BRAND, 5, 0.0, 0.0).unwrap();
        assert_eq!(pair.light.swatches.len(), 5);
        assert_eq!(pair.dark.swatches.len(), 5);
        // The two themes are genuinely different ramps, not one copied twice.
        assert_ne!(pair.light.swatches[0].hex, pair.dark.swatches[0].hex);
    }

    #[test]
    fn an_alpha_ramp_climbs_from_nearly_clear_to_nearly_solid() {
        let ramp = generate_alpha_ramp("#121418").unwrap();
        assert!(ramp.swatches.len() > 1);
        let alphas: Vec<f32> = ramp.swatches.iter().map(|s| s.alpha).collect();
        for pair in alphas.windows(2) {
            assert!(pair[1] > pair[0], "alpha ramp is not ascending: {alphas:?}");
        }
    }

    #[test]
    fn soft_neutrals_stay_the_right_way_round() {
        let soft = derive_soft_neutrals(BRAND, 0.5).unwrap();
        assert!(soft.white.l > soft.black.l);
    }

    #[test]
    fn tinting_pulls_neutrals_toward_the_source_hue() {
        let untinted = tint_neutrals("#ffffff", "#000000", BRAND, 0.0).unwrap();
        let tinted = tint_neutrals("#ffffff", "#000000", BRAND, 1.0).unwrap();
        assert!(tinted.white.c > untinted.white.c, "no tint was applied");
    }

    #[test]
    fn duotone_tinting_can_pull_the_two_ends_apart() {
        let duotone = tint_neutrals_duotone("#ffffff", "#000000", "#ff0000", "#0000ff", 1.0)
            .unwrap();
        // Highlight and shadow are different hues, so the ends must differ.
        assert_ne!(duotone.white.h.round(), duotone.black.h.round());
    }

    #[test]
    fn display_p3_never_offers_less_chroma_than_srgb() {
        for hue in [0.0, 60.0, 120.0, 180.0, 240.0, 300.0] {
            let srgb = max_in_gamut_chroma(0.6, hue, types::Gamut::Srgb);
            let p3 = max_in_gamut_chroma(0.6, hue, types::Gamut::DisplayP3);
            assert!(p3 >= srgb, "P3 was narrower than sRGB at hue {hue}");
            assert!(srgb > 0.0, "sRGB reported no chroma at hue {hue}");
        }
    }

    #[test]
    fn every_painter_fills_exactly_the_rgba_buffer_it_promised() {
        let g = types::Gamut::Srgb;
        assert_eq!(paint_lc_plane(260.0, 8, 5, 0.4, g).len(), 8 * 5 * 4);
        assert_eq!(paint_ch_plane(0.6, 8, 5, 0.4, g).len(), 8 * 5 * 4);
        assert_eq!(paint_lh_plane(0.1, 8, 5, g).len(), 8 * 5 * 4);
        assert_eq!(paint_hue_strip(0.6, 0.1, 8, g).len(), 8 * 4);
        assert_eq!(paint_lightness_strip(0.1, 260.0, 8, g, 0.0, 1.0).len(), 8 * 4);
        assert_eq!(paint_chroma_strip(0.6, 260.0, 8, 0.4, g).len(), 8 * 4);
    }

    #[test]
    fn a_painted_plane_is_not_uniformly_transparent() {
        // A buffer of the right length full of zeroes would pass the length
        // check above while painting nothing.
        let plane = paint_lc_plane(260.0, 16, 16, 0.4, types::Gamut::Srgb);
        assert!(plane.iter().any(|&byte| byte != 0), "plane painted nothing");
    }

    #[test]
    fn assessing_a_ramp_reports_a_foreground_for_every_step() {
        let quality = assess_brand_ramp(0.5557, 0.192, 259.9, types::Gamut::Srgb).unwrap();
        let coverage = quality.foreground_coverage;
        assert_eq!(coverage.fail, 0, "a step has no accessible foreground");
        assert_eq!(coverage.aaa + coverage.aa, quality.steps.len());
        assert_eq!(quality.gamut, types::Gamut::Srgb);
    }

    #[test]
    fn chroma_headroom_never_grants_more_than_was_asked_for() {
        let report = chroma_headroom(0.5557, 0.192, 259.9, types::Gamut::Srgb);
        assert_eq!(report.steps.len(), 10);
        for step in &report.steps {
            assert!(
                step.granted <= step.requested,
                "{} granted more than it requested",
                step.label
            );
        }
    }

    #[test]
    fn parsing_and_describing_a_colour_agree_with_each_other() {
        let parsed = parse_color(BRAND).unwrap();
        let described = describe_oklch(parsed.l, parsed.c, parsed.h);

        assert_eq!(described.hex.to_lowercase(), BRAND);
        assert_eq!(described.oklch, parsed.oklch);
    }

    fn brand_ramp() -> types::Ramp {
        let palette = api::generate(ColorInput::Css("#3b82f6".to_string()))
            .expect("valid input should produce a palette");
        types::Ramp {
            steps: palette.steps().into_iter().map(Into::into).collect(),
        }
    }

    fn white() -> types::SwatchStep {
        harmoni_core::SwatchStep::from_label(1.0, 0.0, 0.0, 50u16).into()
    }

    #[test]
    fn readable_step_returns_the_quietest_step_that_clears_not_the_first() {
        let ramp = brand_ramp();

        let picked = readable_step(ramp.clone(), white(), 4.5).expect("a dark step clears on white");

        // A role wants the least contrast that still passes — a border pushed to
        // body-text weight passes its floor and looks like a mistake.
        let quieter = ramp
            .steps
            .iter()
            .map(|step| {
                let one = types::Ramp { steps: vec![step.clone()] };
                readable_step(one, white(), 4.5).map(|r| r.contrast_ratio)
            })
            .flatten()
            .filter(|ratio| *ratio < picked.contrast_ratio)
            .count();

        assert_eq!(quieter, 0, "a quieter step also cleared 4.5:1");
    }

    #[test]
    fn readable_step_reports_nothing_rather_than_the_least_bad_option() {
        // No step of a ramp reaches 21:1 against white but black itself, so the
        // honest answer is that this role has no colour here.
        assert_eq!(readable_step(brand_ramp(), white(), 21.5), None);
    }

    #[test]
    fn one_ratio_grades_differently_depending_on_what_it_is_for() {
        assert_eq!(grade(4.71, types::ContrastUse::BodyText), types::Grade::Aa);
        assert_eq!(grade(4.71, types::ContrastUse::LargeText), types::Grade::Aaa);
        assert_eq!(grade(4.71, types::ContrastUse::NonText), types::Grade::Aa);
    }

    #[test]
    fn body_text_below_its_own_bar_can_still_pass_at_heading_size() {
        assert_eq!(
            grade(3.5, types::ContrastUse::BodyText),
            types::Grade::LargeTextOnly
        );
    }

    #[test]
    fn non_text_never_reports_the_enhanced_tier_it_has_no_standard_for() {
        assert_eq!(grade(21.0, types::ContrastUse::NonText), types::Grade::Aa);
    }
}

