//! A JS/TS-consumable constants export (RFC 0025 §4/§5) for tokens whose
//! consumers need a real numeric/string value outside the CSS cascade —
//! e.g. `useMediaQuery`'s `matchMedia()` calls, which cannot read a CSS
//! custom property inside a media-query condition.

use crate::token::Token;

/// Render a flat token list as a TS `const` object literal, one property per
/// token's leaf name mapped to its already-formatted CSS value (e.g.
/// `"22.5rem"`). Every key is quoted so a leading-digit name like `2xl` stays
/// a valid object key.
pub fn emit_breakpoints_ts(tokens: &[Token]) -> String {
    let mut out = String::from(
        "// Generated by `primitiv tokens` — do not edit directly.\nexport const breakpoints = {\n",
    );
    for token in tokens {
        let name = token.path.last().expect("token path is never empty");
        out.push_str(&format!("  \"{name}\": \"{}\",\n", token.value));
    }
    out.push_str("} as const;\n");
    out
}
