import type { Metadata } from "next";

import { ColourLibrary } from "@/site/ColourLibrary";

export const metadata: Metadata = {
  title: "Colour library",
  description:
    "Seventeen hue ramps generated by Harmoni, with the text colour that reads best on every swatch.",
};

export default function Page() {
  return <ColourLibrary />;
}
