import type { Metadata } from "next";

import { pageMetadata } from "@/lib/page-metadata";
import { ColourLibrary } from "@/site/ColourLibrary";

export const metadata: Metadata = pageMetadata({
  title: "Colour library",
  description:
    "Seventeen hue ramps generated by Harmoni, with the text colour that reads best on every swatch.",
  path: "/colours/",
});

export default function Page() {
  return <ColourLibrary />;
}
